name: Publish Package to NPM

on:
  release:
    types: [published]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/hako-ui
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: pnpm install
      - name: Set package version
        run: pnpm version ${{ github.ref_name }}
      - name: Build package
        run: pnpm build
      - run: npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
